# Generated by Django 5.2.1 on 2025-07-22 08:08

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_astrocalendarpage_astrocalendarevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='AstroEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('description', wagtail.fields.RichTextField()),
                ('event_type', models.CharField(choices=[('eclipse', 'Eclipse'), ('meteor', 'Meteor Shower'), ('planetary', 'Planetary'), ('other', 'Other')], default='other', max_length=50)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='cms.astrocalendarpage')),
            ],
        ),
        migrations.DeleteModel(
            name='AstroCalendarEvent',
        ),
    ]
