# Generated by Django 5.2.1 on 2025-07-12 19:58

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_blogindexpage_blogpage_delete_homepage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='body',
            field=wagtail.fields.StreamField([('heading', 0), ('subheading', 1), ('paragraph', 2), ('image', 3), ('quote', 4), ('embed', 5), ('html', 6), ('button', 9)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'full title'}), 1: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title'}), 2: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ul', 'ol']}), 3: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 4: ('wagtail.blocks.BlockQuoteBlock', (), {}), 5: ('wagtail.embeds.blocks.EmbedBlock', (), {}), 6: ('wagtail.blocks.RawHTMLBlock', (), {}), 7: ('wagtail.blocks.CharBlock', (), {'required': True}), 8: ('wagtail.blocks.URLBlock', (), {'required': True}), 9: ('wagtail.blocks.StructBlock', [[('text', 7), ('url', 8)]], {})}),
        ),
    ]
