# Generated by Django 5.2.1 on 2025-08-20 19:04

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_gallerypage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleryimage',
            name='caption',
        ),
        migrations.RemoveField(
            model_name='galleryimage',
            name='page',
        ),
        migrations.AlterField(
            model_name='gallerypage',
            name='intro',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='GalleryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('page', modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='cms.gallerypage')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='category',
            field=modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cms.gallerycategory'),
        ),
    ]
