# Generated by Django 5.2.1 on 2025-08-20 19:43

import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_remove_galleryimage_caption_remove_galleryimage_page_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallerycategory',
            name='images',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='+', to='wagtailimages.image'),
        ),
        migrations.DeleteModel(
            name='GalleryImage',
        ),
    ]
